# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c347258858781bb8d31d898c0df13105cac26d36384ad1fc9b441af1c59bb5f7137fef40628b34ed166b8a6c3839fac13e9cf197e03ff3077cf99173134ece26

test:
  secret_key_base: 834ae9e900cfd4c6f681aac42e3e867c02aacb6c3a4470de4b305437533908da9689dd979df7ff9fc1a96d1c6308966509ceb18037f13c9b9125c2e86332335b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
